name: test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
